// src/app/layout.tsx
import type { Metadata } from "next";
import type { Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardNav from "@/components/DashboardNav";
import Providers from "./providers";
import ThemeToggle from "@/components/ThemeToggle";
import LogoutButton from "@/components/LogoutButton";
// import { cookies } from "next/headers";
import Brand from "@/components/Brand";
import { auth } from "@/auth";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Ensure proper scaling on mobile devices
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // NOTE: cookies() is async in Next 15
  //const cookieStore = await cookies();
  //const themeCookie = cookieStore.get("theme")?.value as "dark" | "light" | "system" | undefined;
  //const initialClass = themeCookie === "dark" ? "dark" : "";
  const session = await auth();
  type UserWithRole = { role?: "OWNER" | "CLIENT" | string };
  const role = (session?.user as UserWithRole | undefined)?.role as "OWNER" | "CLIENT" | undefined;
  const ownerEmail = process.env.OWNER_EMAIL || "";

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="light dark" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
      (function () {
        try {
          var ls = null;
          try { ls = localStorage.getItem('theme'); } catch (e) {}
          var m = document.cookie.match(/(?:^|;\\s*)theme=([^;]+)/);
          var cookieTheme = m ? decodeURIComponent(m[1]) : null; // "dark" | "light" | "system"
          var choice = ls || cookieTheme || 'system';

          var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
          var wantDark = choice === 'dark' || (choice === 'system' && prefersDark);

          var root = document.documentElement;
          if (wantDark) root.classList.add('dark'); else root.classList.remove('dark');
          root.style.colorScheme = wantDark ? 'dark' : 'light';
        } catch (_) {}
      })();
            `.trim(),
          }}
        />
      </head>


        <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen
                  bg-white text-zinc-900 dark:bg-zinc-900 dark:text-zinc-100`}>
        <Providers>
          <header className="sticky top-0 z-40 border-b bg-white/70 backdrop-blur dark:bg-[rgb(var(--card))]/70">
            <div className="max-w-4xl mx-auto px-4 py-2">
              <div className="flex items-center gap-3 md:gap-4 h-12 sm:h-auto">
                {/* Left: brand + nav */}
                <div className="flex items-center gap-4 flex-1 min-w-0">
                  <Brand compact />
                  <DashboardNav />
                </div>

                {/* Right side: divider + Theme + Logout */}
                <div className="ml-auto flex items-center gap-3 md:gap-4 pl-4 border-l border-zinc-200 dark:border-zinc-800">
                  <ThemeToggle />
                  <LogoutButton />

                </div>
              </div>
            </div>
          </header>

          <main className="max-w-4xl mx-auto p-4 sm:p-6">{children}</main>

          {role === "CLIENT" && ownerEmail && (
            <footer className="max-w-4xl mx-auto px-4 pb-6 pt-2 text-sm text-gray-600">
              <div className="border-t pt-3">
                Contact: <a className="underline" href={`mailto:${ownerEmail}`}>{ownerEmail}</a>
              </div>
            </footer>
          )}
        </Providers>
      </body>
    </html>
  );
}
