"""
Feature configuration for the Home Credit Default project.

This module centralizes long, repeated configuration objects such as
the list of selected features for the production model and the
categorical grouping maps used during feature engineering.

Keeping these in a dedicated file improves readability in the main
preprocessing code and makes it easier to reuse or update them
consistently across the project.
"""

from __future__ import annotations


selected_features = [
    "EXT_SOURCE_3",
    "EXT_SOURCE_2",
    "EXT_SOURCE_1",
    "DAYS_EMPLOYED",
    "credit_annuity_ratio",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "age_score_ratio",
    "NAME_EDUCATION_TYPE_Higher_education",
    "p_NUM_DAYS_LAST_DUE_1ST_VERSION_max",
    "score_credit_ratio",
    "NAME_FAMILY_STATUS_Married",
    "CODE_GENDER_F",
    "BUREAU_bureau_NUM_AMT_CREDIT_SUM_DEBT_mean_mean",
    "DAYS_BIRTH",
    "p_NUM_ip_NUM_AMT_PAYMENT_min_mean",
    "p_NUM_ip_NUM_late_payment_lag_max_mean",
    "FLAG_OWN_CAR_N",
    "prev_cat_CNT_NAME_CONTRACT_STATUS_Refused",
    "CODE_GENDER_M",
    "BUREAU_bureau_NUM_AMT_CREDIT_MAX_OVERDUE_mean_mean",
    "BUREAU_bureau_CNT_CREDIT_ACTIVE_Closed_mean",
    "prev_cat_CNT_NAME_YIELD_GROUP_low_action",
    "LAST3_ip_NUM_late_payment_lag_max_mean",
    "ORGANIZATION_TYPE_GROUPED_Public_Sector",
    "BUREAU_bureau_NUM_credit_usage_mean_mean",
    "SUM_FLAG_DOCUMENT",
    "AMT_CREDIT",
    "REGION_RATING_CLIENT_W_CITY",
    "p_NUM_AMT_DOWN_PAYMENT_max",
    "prev_cat_CNT_NAME_YIELD_GROUP_high",
    "DAYS_ID_PUBLISH",
    "p_NUM_DAYS_LAST_DUE_1ST_VERSION_mean",
    "p_NUM_ccb_NUM_CNT_DRAWINGS_ATM_CURRENT_mean_max",
    "p_NUM_DAYS_LAST_DUE_max",
    "p_NUM_ip_NUM_AMT_PAYMENT_min_max",
    "p_NUM_ip_NUM_late_payment_lag_max_max",
    "BUREAU_bureau_NUM_DAYS_CREDIT_mean_mean",
    "BUREAU_bureau_NUM_bureau_debt_over_limit_mean_mean",
    "p_NUM_POS_NUM_CNT_INSTALMENT_FUTURE_min_mean",
    "DEF_60_CNT_SOCIAL_CIRCLE",
    "FLAG_DOCUMENT_3",
    "p_NUM_POS_NUM_MONTHS_BALANCE_max_max",
    "p_NUM_POS_NUM_CNT_INSTALMENT_FUTURE_mean_mean",
    "BUREAU_bureau_NUM_AMT_CREDIT_SUM_mean_mean",
    "OWN_CAR_AGE",
    "prev_cat_CNT_PRODUCT_COMBINATION_Cash_X_Sell__low",
    "LAST3_ip_NUM_late_payment_lag_max_max",
    "prev_cat_CNT_CODE_REJECT_REASON_XAP",
    "p_NUM_ip_NUM_NUM_INSTALMENT_VERSION_mean_max",
    "NAME_EDUCATION_TYPE_Secondary_secondary_special",
    "BUREAU_bureau_CNT_CREDIT_TYPE_Mortgage_mean",
    "NAME_CONTRACT_TYPE_Cash_loans",
    "LAST3_ip_NUM_AMT_PAYMENT_min_max",
    "REG_CITY_NOT_LIVE_CITY",
    "p_NUM_POS_NUM_CNT_INSTALMENT_std_mean",
    "LAST3_ip_NUM_late_payment_lag_mean_max",
    "DAYS_LAST_PHONE_CHANGE",
    "p_NUM_AMT_ANNUITY_mean",
    "LAST3_ip_NUM_DAYS_INSTALMENT_std_max",
    "prev_cat_CNT_NAME_PRODUCT_TYPE_walk_in",
    "LAST3_POS_NUM_CNT_INSTALMENT_FUTURE_mean_std",
    "BUREAU_bureau_NUM_DAYS_CREDIT_ENDDATE_mean_mean",
    "AMT_REQ_CREDIT_BUREAU_QRT",
    "p_NUM_POS_NUM_CNT_INSTALMENT_std_max",
    "p_NUM_ip_NUM_NUM_INSTALMENT_VERSION_std_max",
    "LAST3_ip_NUM_AMT_PAYMENT_min_mean",
    "p_NUM_AMT_DOWN_PAYMENT_mean",
    "LAST1_ip_NUM_late_payment_lag_max_mean",
    "NAME_INCOME_TYPE_GROUPED_Working",
    "DAYS_REGISTRATION",
    "p_NUM_POS_NUM_MONTHS_BALANCE_mean_max",
    "p_NUM_ip_NUM_NUM_INSTALMENT_VERSION_std_mean",
    "BUREAU_bureau_CNT_CREDIT_TYPE_Microloan_mean",
    "p_NUM_CNT_PAYMENT_mean",
    "p_NUM_ip_NUM_AMT_INSTALMENT_min_mean",
    "p_NUM_ip_NUM_AMT_PAYMENT_mean_max",
    "income_goods_ratio",
    "prev_cat_CNT_PRODUCT_COMBINATION_POS_industry_with_interest",
    "p_NUM_ip_NUM_DAYS_ENTRY_PAYMENT_max_max",
    "APARTMENTS_MEDI",
    "LAST3_ip_NUM_late_payment_lag_std_mean",
    "p_NUM_ip_NUM_AMT_INSTALMENT_min_max",
    "AMT_INCOME_TOTAL",
    "LAST3_ccb_NUM_CNT_DRAWINGS_CURRENT_std_mean",
    "p_NUM_ccb_NUM_CNT_DRAWINGS_CURRENT_std_max",
    "BUREAU_bureau_NUM_AMT_CREDIT_SUM_LIMIT_mean_mean",
    "BUREAU_bureau_CNT_CREDIT_ACTIVE_Active_mean",
    "p_NUM_POS_NUM_credit_term_ratio_mean_mean",
    "p_NUM_POS_NUM_CNT_INSTALMENT_FUTURE_min_max",
    "p_NUM_POS_NUM_CNT_INSTALMENT_FUTURE_mean_max",
    "LAST3_ip_NUM_late_payment_lag_std_max",
    "p_NUM_ip_NUM_DAYS_INSTALMENT_std_max",
    "DEF_30_CNT_SOCIAL_CIRCLE",
    "prev_cat_CNT_NAME_GOODS_CATEGORY_Furniture",
    "p_NUM_ccb_NUM_CNT_DRAWINGS_ATM_CURRENT_mean_mean",
    "LAST3_DAYS_LAST_DUE_1ST_VERSION_max",
    "p_NUM_RATE_DOWN_PAYMENT_max",
    "LAST3_POS_NUM_SK_DPD_DEF_std_std",
    "p_NUM_ip_NUM_DAYS_INSTALMENT_min_mean",
    "p_NUM_HOUR_APPR_PROCESS_START_max",
    "p_NUM_ccb_NUM_AMT_BALANCE_max_max",
    "p_NUM_POS_CNT_NAME_CONTRACT_STATUS_Active_max",
    "p_NUM_ip_NUM_DAYS_ENTRY_PAYMENT_std_max",
    "LAST3_HOUR_APPR_PROCESS_START_max",
    "LAST3_ip_NUM_DAYS_ENTRY_PAYMENT_std_max",
    "APARTMENTS_AVG",
    "p_NUM_DAYS_FIRST_DRAWING_max",
    "BUREAU_bureau_CNT_CREDIT_TYPE_Car_loan_mean",
    "OCCUPATION_TYPE_GROUPED_Core_staff",
    "p_NUM_RATE_DOWN_PAYMENT_mean",
    "LAST3_RATE_DOWN_PAYMENT_max",
    "prev_cat_CNT_NAME_PRODUCT_TYPE_XNA",
    "p_NUM_AMT_GOODS_PRICE_mean",
    "LAST3_RATE_DOWN_PAYMENT_std",
    "LAST1_ip_NUM_AMT_PAYMENT_min_mean",
    "p_NUM_HOUR_APPR_PROCESS_START_mean",
    "LAST1_AMT_GOODS_PRICE_mean",
    "LAST1_HOUR_APPR_PROCESS_START_mean",
    "p_NUM_CNT_PAYMENT_max",
    "p_NUM_POS_CNT_NAME_CONTRACT_STATUS_Active_mean",
    "LAST3_ip_NUM_DAYS_ENTRY_PAYMENT_max_max",
    "LAST3_POS_NUM_CNT_INSTALMENT_mean_std",
    "p_NUM_DAYS_DECISION_mean",
    "OCCUPATION_TYPE_GROUPED_Drivers",
    "REGION_POPULATION_RELATIVE",
    "BUREAU_bureau_NUM_bureau_CNT_STATUS_1_mean_mean",
    "LAST3_POS_NUM_credit_term_ratio_mean_mean",
    "p_NUM_ip_NUM_DAYS_ENTRY_PAYMENT_std_mean",
    "LAST3_CNT_PAYMENT_mean",
    "LAST1_ip_NUM_late_payment_lag_std_mean",
    "p_NUM_ccb_NUM_CNT_DRAWINGS_ATM_CURRENT_std_mean",
    "prev_cat_CNT_CODE_REJECT_REASON_LIMIT",
    "ORGANIZATION_TYPE_GROUPED_Self_employed",
    "BUREAU_bureau_NUM_bureau_CNT_STATUS_0_mean_mean",
    "LAST3_AMT_ANNUITY_std",
    "p_NUM_ccb_NUM_AMT_CREDIT_LIMIT_ACTUAL_mean_mean",
    "p_NUM_DAYS_TERMINATION_max",
    "LAST3_ip_NUM_DAYS_ENTRY_PAYMENT_std_mean",
    "LAST3_AMT_CREDIT_mean",
    "prev_cat_CNT_NAME_CONTRACT_STATUS_Approved",
    "TOTALAREA_MODE",
    "YEARS_BEGINEXPLUATATION_MEDI",
    "LAST3_DAYS_LAST_DUE_1ST_VERSION_std",
    "prev_cat_CNT_NAME_CLIENT_TYPE_New",
    "p_NUM_POS_NUM_SK_DPD_DEF_std_max",
    "LAST3_HOUR_APPR_PROCESS_START_std",
    "p_NUM_ip_NUM_AMT_PAYMENT_max_max",
    "p_NUM_POS_NUM_credit_term_ratio_min_mean",
    "prev_cat_CNT_CHANNEL_TYPE_AP___Cash_loan_",
    "LAST3_CNT_PAYMENT_max",
    "p_NUM_ccb_NUM_AMT_RECEIVABLE_PRINCIPAL_mean_max",
    "BUREAU_bureau_NUM_DAYS_CREDIT_UPDATE_mean_mean",
    "BUREAU_bureau_NUM_bureau_NUM_MONTHS_BALANCE_std_mean_mean",
    "p_NUM_AMT_APPLICATION_max",
    "YEARS_BEGINEXPLUATATION_MODE",
    "LAST3_ip_NUM_late_payment_lag_max_std",
    "p_NUM_DAYS_LAST_DUE_mean",
    "LAST3_AMT_ANNUITY_max",
    "BUREAU_bureau_NUM_DAYS_ENDDATE_FACT_mean_mean",
    "p_NUM_ip_NUM_DAYS_INSTALMENT_std_mean",
    "prev_cat_CNT_CODE_REJECT_REASON_HC",
    "LAST3_POS_NUM_credit_term_ratio_std_mean",
    "prev_cat_CNT_PRODUCT_COMBINATION_Cash_X_Sell__high",
    "LAST3_POS_NUM_SK_DPD_DEF_std_mean",
    "LAST3_RATE_DOWN_PAYMENT_mean",
    "p_NUM_ccb_NUM_CNT_DRAWINGS_CURRENT_mean_mean",
    "p_NUM_ip_NUM_AMT_PAYMENT_max_mean",
    "p_NUM_ccb_NUM_max_drawings_receivable_ratio_std_max",
    "p_NUM_ip_NUM_late_payment_lag_std_mean",
    "p_NUM_ccb_NUM_CNT_DRAWINGS_CURRENT_mean_max",
    "LAST3_POS_NUM_credit_term_ratio_min_std",
    "OCCUPATION_TYPE_GROUPED_Accountants",
    "p_NUM_ccb_NUM_max_drawings_receivable_ratio_mean_mean",
    "p_NUM_DAYS_FIRST_DRAWING_mean",
    "OCCUPATION_TYPE_GROUPED_Laborers",
    "LAST3_AMT_DOWN_PAYMENT_max",
    "LAST1_ip_NUM_late_payment_lag_mean_mean",
    "YEARS_BUILD_MODE",
    "p_NUM_ip_NUM_NUM_INSTALMENT_VERSION_mean_mean",
    "LAST3_ip_NUM_NUM_INSTALMENT_VERSION_std_mean",
    "LAST3_ip_NUM_DAYS_INSTALMENT_min_mean",
    "p_NUM_DAYS_DECISION_max",
    "p_NUM_POS_NUM_CNT_INSTALMENT_FUTURE_std_mean",
    "p_NUM_POS_NUM_credit_term_ratio_std_max",
    "p_NUM_ccb_NUM_max_drawings_receivable_ratio_max_max",
    "prev_cat_CNT_CHANNEL_TYPE_Channel_of_corporate_sales",
    "LAST3_POS_NUM_SK_DPD_DEF_mean_mean",
    "LAST3_ip_NUM_NUM_INSTALMENT_VERSION_mean_mean",
    "p_NUM_ccb_NUM_AMT_BALANCE_mean_mean",
    "p_NUM_ip_NUM_AMT_PAYMENT_mean_mean",
    "LAST3_ip_NUM_AMT_INSTALMENT_min_max",
    "p_NUM_ip_NUM_NUM_INSTALMENT_VERSION_max_max",
    "LAST1_SELLERPLACE_AREA_mean",
    "LAST1_ip_NUM_DAYS_INSTALMENT_std_mean",
    "p_NUM_ip_NUM_late_payment_lag_mean_mean",
    "LAST1_DAYS_TERMINATION_mean",
    "YEARS_BEGINEXPLUATATION_AVG",
    "LAST3_ip_NUM_late_payment_lag_min_std",
    "LAST3_SELLERPLACE_AREA_mean",
    "p_NUM_POS_NUM_SK_DPD_DEF_max_mean",
    "LAST3_ip_NUM_NUM_INSTALMENT_NUMBER_max_max",
    "p_NUM_SELLERPLACE_AREA_max",
    "LIVINGAPARTMENTS_MODE",
    "ORGANIZATION_TYPE_GROUPED_Finance",
    "LAST3_ip_NUM_NUM_INSTALMENT_VERSION_mean_max",
    "BUREAU_bureau_NUM_bureau_CNT_STATUS_C_mean_mean",
    "p_NUM_ip_NUM_AMT_PAYMENT_std_mean",
    "LAST3_DAYS_DECISION_std",
    "LAST3_ip_NUM_AMT_INSTALMENT_mean_max",
    "LAST3_POS_NUM_SK_DPD_mean_std",
    "LAST3_SELLERPLACE_AREA_std",
    "prev_cat_CNT_PRODUCT_COMBINATION_POS_industry_without_interest",
    "p_NUM_ip_NUM_AMT_INSTALMENT_std_mean",
    "p_NUM_ccb_NUM_AMT_CREDIT_LIMIT_ACTUAL_mean_max",
    "p_NUM_ccb_NUM_AMT_DRAWINGS_CURRENT_std_max",
    "p_NUM_ip_NUM_late_payment_lag_mean_max",
    "LAST3_HOUR_APPR_PROCESS_START_mean",
    "p_NUM_POS_NUM_MONTHS_BALANCE_std_mean",
    "LAST3_DAYS_TERMINATION_std",
    "LAST3_AMT_GOODS_PRICE_mean",
    "LAST3_POS_NUM_credit_term_ratio_min_max",
    "LAST3_ip_NUM_AMT_INSTALMENT_max_mean",
    "LAST3_AMT_ANNUITY_mean",
    "LAST3_POS_NUM_SK_DPD_DEF_std_max",
    "p_NUM_POS_NUM_CNT_INSTALMENT_max_mean",
    "p_NUM_ip_NUM_late_payment_lag_std_max",
    "LAST3_ip_NUM_DAYS_INSTALMENT_std_mean",
    "LAST3_POS_NUM_credit_term_ratio_mean_max",
    "LAST3_DAYS_LAST_DUE_max",
    "LAST3_DAYS_TERMINATION_max",
    "LAST3_POS_NUM_CNT_INSTALMENT_FUTURE_mean_mean",
    "LAST3_DAYS_DECISION_mean",
    "p_NUM_ccb_NUM_AMT_PAYMENT_TOTAL_CURRENT_mean_mean",
    "LIVINGAREA_MODE",
    "p_NUM_POS_NUM_MONTHS_BALANCE_std_max",
    "p_NUM_ip_NUM_DAYS_INSTALMENT_mean_max",
    "prev_cat_CNT_NAME_CONTRACT_TYPE_Consumer_loans",
    "LAST1_ip_NUM_DAYS_ENTRY_PAYMENT_max_mean",
    "p_NUM_ip_NUM_DAYS_INSTALMENT_mean_mean",
    "YEARS_BUILD_AVG",
    "p_NUM_POS_NUM_MONTHS_BALANCE_min_mean",
    "LAST3_ccb_NUM_CNT_DRAWINGS_CURRENT_mean_mean",
    "LAST3_POS_NUM_CNT_INSTALMENT_std_mean",
    "FLOORSMAX_AVG",
    "LAST3_ip_NUM_late_payment_lag_mean_mean",
    "LAST3_ip_NUM_AMT_INSTALMENT_min_mean",
    "NAME_INCOME_TYPE_GROUPED_State_servant",
    "p_NUM_POS_NUM_MONTHS_BALANCE_min_max",
    "prev_cat_CNT_NAME_PORTFOLIO_POS",
    "p_NUM_ccb_NUM_CNT_DRAWINGS_ATM_CURRENT_std_max",
    "p_NUM_ip_NUM_AMT_INSTALMENT_max_mean",
    "LAST1_ip_NUM_AMT_INSTALMENT_min_mean",
    "prev_cat_CNT_NAME_YIELD_GROUP_low_normal",
    "LAST3_POS_NUM_CNT_INSTALMENT_std_std",
    "LAST3_ip_NUM_late_payment_lag_std_std",
    "p_NUM_ip_NUM_DAYS_INSTALMENT_max_max",
    "LAST3_POS_NUM_SK_DPD_max_std",
    "LAST3_ip_NUM_late_payment_lag_min_max",
    "LAST1_ip_NUM_NUM_INSTALMENT_VERSION_mean_mean",
    "LAST3_ip_NUM_late_payment_lag_mean_std",
    "LAST1_ip_NUM_AMT_INSTALMENT_std_mean",
    "FLAG_WORK_PHONE",
    "BUREAU_bureau_NUM_bureau_NUM_MONTHS_BALANCE_mean_mean_mean",
    "APARTMENTS_MODE",
    "p_NUM_POS_NUM_CNT_INSTALMENT_FUTURE_std_max",
    "LAST3_ip_NUM_NUM_INSTALMENT_VERSION_std_max",
    "LAST3_POS_NUM_credit_term_ratio_mean_std",
    "LAST3_POS_NUM_MONTHS_BALANCE_std_std",
    "prev_cat_CNT_PRODUCT_COMBINATION_POS_household_without_interest",
    "LAST3_CNT_PAYMENT_std",
    "LANDAREA_AVG",
    "p_NUM_AMT_CREDIT_mean",
    "p_NUM_ccb_NUM_max_drawings_receivable_ratio_std_mean",
    "BUREAU_bureau_NUM_bureau_CNT_STATUS_X_mean_mean",
    "BUREAU_bureau_NUM_AMT_ANNUITY_mean_mean",
    "BUREAU_bureau_CNT_CREDIT_TYPE_Consumer_credit_mean",
    "LAST3_ip_NUM_DAYS_INSTALMENT_min_std",
    "LAST3_AMT_DOWN_PAYMENT_mean",
    "p_NUM_ip_NUM_AMT_INSTALMENT_max_max",
    "BUREAU_bureau_NUM_bureau_NUM_MONTHS_BALANCE_min_mean_mean",
    "LAST1_RATE_DOWN_PAYMENT_mean",
    "p_NUM_POS_NUM_MONTHS_BALANCE_mean_mean",
    "LAST3_ip_NUM_DAYS_INSTALMENT_mean_std",
    "LIVINGAREA_AVG",
    "LAST3_DAYS_FIRST_DUE_mean",
    "LAST3_POS_NUM_MONTHS_BALANCE_min_mean",
    "LAST3_ip_NUM_late_payment_lag_min_mean",
    "p_NUM_POS_NUM_credit_term_ratio_min_max",
    "LAST3_ccb_NUM_AMT_INST_MIN_REGULARITY_std_mean",
    "NONLIVINGAREA_AVG",
    "LAST3_ip_NUM_DAYS_ENTRY_PAYMENT_mean_mean",
    "p_NUM_ccb_NUM_AMT_PAYMENT_CURRENT_max_mean",
    "LAST3_POS_CNT_NAME_CONTRACT_STATUS_Active_max",
    "p_NUM_POS_NUM_SK_DPD_DEF_max_max",
    "LAST1_POS_NUM_credit_term_ratio_mean_mean",
    "BUREAU_bureau_NUM_AMT_CREDIT_SUM_OVERDUE_mean_mean",
    "FLOORSMAX_MEDI",
    "LAST1_POS_NUM_credit_term_ratio_std_mean",
    "LAST3_ip_NUM_NUM_INSTALMENT_NUMBER_std_max",
    "p_NUM_ip_NUM_late_payment_lag_min_max",
    "LAST1_ip_NUM_DAYS_ENTRY_PAYMENT_min_mean",
    "prev_cat_CNT_NAME_SELLER_INDUSTRY_Connectivity",
    "LAST1_POS_NUM_SK_DPD_std_mean",
    "LAST1_ccb_NUM_CNT_DRAWINGS_CURRENT_std_mean",
    "LAST3_POS_CNT_NAME_CONTRACT_STATUS_Active_std",
    "p_NUM_ccb_NUM_AMT_PAYMENT_CURRENT_mean_mean",
    "p_NUM_ccb_NUM_AMT_RECEIVABLE_PRINCIPAL_mean_mean",
    "LAST1_DAYS_LAST_DUE_mean",
    "LAST3_POS_NUM_CNT_INSTALMENT_FUTURE_min_max",
    "p_NUM_SELLERPLACE_AREA_mean",
    "p_NUM_ip_NUM_DAYS_ENTRY_PAYMENT_min_mean",
    "LAST1_POS_NUM_MONTHS_BALANCE_mean_mean",
    "LAST1_ip_NUM_AMT_PAYMENT_max_mean",
    "LAST3_ip_NUM_AMT_PAYMENT_std_mean",
    "p_NUM_POS_NUM_SK_DPD_DEF_std_mean",
    "p_NUM_POS_NUM_CNT_INSTALMENT_mean_max",
    "LAST1_DAYS_LAST_DUE_1ST_VERSION_mean",
    "LAST3_ccb_NUM_max_drawings_receivable_ratio_mean_mean",
    "LAST3_AMT_APPLICATION_std",
    "p_NUM_ip_NUM_late_payment_lag_min_mean",
    "LIVINGAPARTMENTS_AVG",
    "LAST3_POS_NUM_credit_term_ratio_std_std",
    "p_NUM_ccb_NUM_AMT_CREDIT_LIMIT_ACTUAL_min_mean",
    "LAST3_POS_NUM_CNT_INSTALMENT_FUTURE_min_mean",
    "p_NUM_ccb_NUM_CNT_DRAWINGS_CURRENT_max_max",
    "p_NUM_ccb_NUM_AMT_BALANCE_min_max",
    "LAST1_POS_CNT_NAME_CONTRACT_STATUS_Active_mean",
    "LAST1_ip_NUM_AMT_INSTALMENT_mean_mean",
    "LAST3_ccb_NUM_AMT_INST_MIN_REGULARITY_max_mean",
    "p_NUM_ip_NUM_NUM_INSTALMENT_NUMBER_mean_mean",
    "p_NUM_ccb_NUM_CNT_INSTALMENT_MATURE_CUM_std_mean",
    "HOUR_APPR_PROCESS_START",
    "LAST3_ccb_NUM_AMT_BALANCE_mean_max",
    "LAST3_ip_NUM_AMT_INSTALMENT_max_max",
    "LAST3_POS_CNT_NAME_CONTRACT_STATUS_Active_mean",
    "LIVINGAPARTMENTS_MEDI",
    "OBS_60_CNT_SOCIAL_CIRCLE",
    "prev_cat_CNT_NAME_GOODS_CATEGORY_Photo___Cinema_Equipment",
    "BASEMENTAREA_AVG",
    "LAST3_DAYS_FIRST_DRAWING_mean",
    "LAST1_ip_NUM_AMT_PAYMENT_std_mean",
    "FLAG_DOCUMENT_11",
    "BASEMENTAREA_MEDI",
    "p_NUM_AMT_CREDIT_max",
    "p_NUM_AMT_APPLICATION_mean",
    "LAST3_ip_NUM_AMT_PAYMENT_mean_max",
    "LAST3_ccb_NUM_CNT_DRAWINGS_ATM_CURRENT_std_mean",
    "BUREAU_bureau_NUM_bureau_NUM_MONTHS_BALANCE_max_mean_mean",
    "p_NUM_ccb_NUM_AMT_DRAWINGS_CURRENT_mean_mean",
    "LAST3_POS_NUM_MONTHS_BALANCE_std_mean",
    "LAST3_POS_NUM_CNT_INSTALMENT_min_mean",
    "LAST1_POS_NUM_CNT_INSTALMENT_FUTURE_std_mean",
    "LAST3_ip_NUM_AMT_PAYMENT_max_std",
    "LAST3_ip_NUM_DAYS_ENTRY_PAYMENT_mean_std",
    "LAST3_POS_CNT_NAME_CONTRACT_STATUS_Signed_mean",
    "p_NUM_ccb_NUM_AMT_RECIVABLE_mean_max",
    "BUREAU_bureau_CNT_CREDIT_TYPE_Credit_card_mean",
    "LAST1_POS_NUM_CNT_INSTALMENT_FUTURE_mean_mean",
    "p_NUM_ip_NUM_NUM_INSTALMENT_NUMBER_mean_max",
    "LAST3_DAYS_LAST_DUE_std",
    "LAST3_ip_NUM_DAYS_INSTALMENT_max_std",
    "LAST3_ip_NUM_AMT_PAYMENT_std_std",
    "p_NUM_POS_NUM_CNT_INSTALMENT_mean_mean",
    "p_NUM_ccb_NUM_AMT_BALANCE_mean_max",
    "LAST1_ip_NUM_DAYS_INSTALMENT_mean_mean",
    "LAST3_POS_NUM_CNT_INSTALMENT_mean_mean",
    "prev_cat_CNT_NAME_CASH_LOAN_PURPOSE_XAP",
    "LAST3_POS_NUM_CNT_INSTALMENT_std_max",
    "LAST1_ip_NUM_NUM_INSTALMENT_VERSION_std_mean",
    "LAST3_ip_NUM_AMT_INSTALMENT_max_std",
    "LAST3_DAYS_LAST_DUE_mean",
    "LAST3_ip_NUM_DAYS_ENTRY_PAYMENT_max_std",
    "LAST1_AMT_ANNUITY_mean",
    "p_NUM_ccb_NUM_AMT_BALANCE_std_mean",
]


OCCUPATION_TYPE_GROUP_MAP = {
    "Accountants": "Accountants",
    "Cleaning staff": "Service",
    "Cooking staff": "Service",
    "Core staff": "Core staff",
    "Drivers": "Drivers",
    "HR staff": "Other",
    "High skill tech staff": "Tech",
    "IT staff": "Tech",
    "Laborers": "Laborers",
    "Low-skil Laborers": "Laborers",
    "Managers": "Managers",
    "Medicine staff": "Medicine",
    "Private service staff": "Other",
    "Realty agents": "Other",
    "Sales staff": "Sales",
    "Secretaries": "Other",
    "Security staff": "Other",
    "Waiters/barmen staff": "Service",
}


INCOME_TYPE_GROUP_MAP = {
    "Businessman": "Other",
    "Commercial associate": "Commercial associate",
    "Pensioner": "Pensioner",
    "State servant": "State servant",
    "Student": "Other",
    "Unemployed": "Other",
    "Working": "Working",
}


ORGANIZATION_TYPE_GROUP_MAP = {
    "Business Entity Type 3": "Business",
    "Business Entity Type 2": "Business",
    "Business Entity Type 1 ": "Business",
    "XNA": "Unknown",
    "Self-employed": "Self-employed",
    "Other": "Other",
    "Medicine": "Public Sector",
    "Government": "Public Sector",
    "School": "Public Sector",
    "Kindergarten": "Public Sector",
    "Housing": "Public Sector",
    "Military": "Public Sector",
    "Police": "Public Sector",
    "Postal": "Public Sector",
    "Security Ministries": "Public Sector",
    "University": "Public Sector",
    "Emergency": "Public Sector",
    "Trade: type 7": "Trade",
    "Trade: type 6": "Trade",
    "Trade: type 5": "Trade",
    "Trade: type 4": "Trade",
    "Trade: type 3": "Trade",
    "Trade: type 2": "Trade",
    "Trade: type 1": "Trade",
    "Electricity ": "Trade",
    "Construction": "Trade",
    "Transport: type 4": "Transport",
    "Transport: type 3": "Transport",
    "Transport: type 2": "Transport",
    "Transport: type 1": "Transport",
    "Industry: type 13": "Industry",
    "Industry: type 12 ": "Industry",
    "Industry: type 10": "Industry",
    "Industry: type 9": "Industry",
    "Industry: type 8": "Industry",
    "Industry: type 7": "Industry",
    "Industry: type 6": "Industry",
    "Industry: type 5": "Industry",
    "Industry: type 4 ": "Industry",
    "Industry: type 3": "Industry",
    "Industry: type 2 ": "Industry",
    "Industry: type 1 ": "Industry",
    "Industry: type 11": "Industry",
    "Agriculture": "Industry",
    "Services ": "Service",
    "Hotel": "Service",
    "Restaurant": "Service",
    "Cleaning": "Service",
    "Realtor": "Service",
    "Legal Services": "Service",
    "Advertising": "Other",
    "Religion": "Other",
    "Culture": "Other",
    "Bank": "Finance",
    "Insurance": "Finance",
    "Telecom": "Other",
    "Mobile": "Other",
}


HOUSING_TYPE_GROUP_MAP = {
    "House / apartment": "House / apartment",
    "Municipal apartment": "Other apartment",
    "Office apartment": "Other apartment",
    "Rented apartment": "Other apartment",
    "With parents": "With parents",
    "Co-op apartment": "Other apartment",
}

# Public alias used by serving / Streamlit code
SELECTED_FEATURES = selected_features
