"""baseline schema

Revision ID: base_0001
Revises:
Create Date: 2025-09-15 12:53:23.148665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "base_0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability_rules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_local", sa.Time(), nullable=False),
        sa.Column("end_local", sa.Time(), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("buffer_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["auth.User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id",
            "weekday",
            "start_local",
            "end_local",
            "slot_minutes",
            "buffer_minutes",
            name="uq_rule_owner_day_window_len_buf",
        ),
    )
    op.create_index(
        op.f("ix_availability_rules_owner_id"),
        "availability_rules",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "client_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("client_user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_user_id"], ["auth.User.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["auth.User.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id", "client_user_id", name="uq_owner_client"),
    )
    op.create_index(
        op.f("ix_client_accounts_client_user_id"),
        "client_accounts",
        ["client_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_accounts_id"), "client_accounts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_client_accounts_owner_user_id"),
        "client_accounts",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "special_openings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("buffer_minutes", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["auth.User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_special_openings_owner_id"),
        "special_openings",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "timeoffs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["auth.User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_timeoffs_owner_id"), "timeoffs", ["owner_id"], unique=False
    )
    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["client_accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_people_account_id"), "people", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_people_id"), "people", ["id"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["auth.User.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["auth.User.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "start_utc", name="uq_owner_start"),
    )
    op.create_index(
        op.f("ix_appointments_client_id"), "appointments", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_owner_id"), "appointments", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_person_id"), "appointments", ["person_id"], unique=False
    )
    # op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('alembic_version',
    # sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    # )
    op.drop_index(op.f("ix_appointments_person_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_owner_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_client_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_people_id"), table_name="people")
    op.drop_index(op.f("ix_people_account_id"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_timeoffs_owner_id"), table_name="timeoffs")
    op.drop_table("timeoffs")
    op.drop_index(op.f("ix_special_openings_owner_id"), table_name="special_openings")
    op.drop_table("special_openings")
    op.drop_index(
        op.f("ix_client_accounts_owner_user_id"), table_name="client_accounts"
    )
    op.drop_index(op.f("ix_client_accounts_id"), table_name="client_accounts")
    op.drop_index(
        op.f("ix_client_accounts_client_user_id"), table_name="client_accounts"
    )
    op.drop_table("client_accounts")
    op.drop_index(
        op.f("ix_availability_rules_owner_id"), table_name="availability_rules"
    )
    op.drop_table("availability_rules")
    # ### end Alembic commands ###
