[project]
name = "aieng-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=23.2.1",
    "asgi-lifespan>=2.1.0",
    "axios>=0.4.0",
    "black>=23.11.0",
    "bs4>=0.0.2",
    "cryptography>=41.0.8",
    "docker>=7.1.0",
    "dotenv>=0.9.9",
    "faker>=37.6.0",
    "fastapi>=0.111",
    "flake8>=6.1.0",
    "freezegun>=1.5.5",
    "gcloud>=0.18.3",
    "google-cloud-storage>=3.3.1",
    "httpx[http2]>=0.27",
    "ipykernel>=6.30.1",
    "jinja2>=3.1.6",
    "langchain>=0.2.13",
    "langchain-community>=0.0.10",
    "langchain-openai>=0.1.22",
    "langchain-qdrant>=0.2.0",
    "langchain-text-splitters>=0.2.2",
    "langchainhub>=0.1.21",
    "loguru>=0.7",
    "mcp>=1.13.1",
    "mcp-streamablehttp-proxy>=0.2.0",
    "node>=1.2.2",
    "numpy>=1.26",
    "nvm>=1.0.21",
    "openai>=1.40",
    "pandas>=2.2",
    "pycountry>=24.6.1",
    "pydantic>=2.8",
    "itsdangerous>=2.2",
    "pymupdf>=1.23.14",
    "pypdf>=3.17.4",
    "pytest>=7.4.3",
    "pytest-asyncio>=0.21.1",
    "pytest-cov>=6.2.1",
    "pytest-dotenv>=0.5.2",
    "python-dotenv>=1.0",
    "python-multipart>=0.0.6",
    "qdrant-client>=1.15.1",
    "rank-bm25>=0.2.2",
    "rapidfuzz>=3.14.0",
    "redis>=6.4.0",
    "reportlab>=4.4.3",
    "respx>=0.22.0",
    "scipy>=1.13",
    "tiktoken>=0.7",
    "typing-extensions>=4.8.0",
    "uvicorn[standard]>=0.30",
    "weasyprint>=66.0",
    "world-bank-mcp-server>=0.1.0",
]
