[pytest]
filterwarnings =
    ignore:The `__fields__` attribute is deprecated, use `model_fields` instead:pydantic.PydanticDeprecatedSince20:langchain_core.tools.base
    ignore:The `__fields__` attribute is deprecated, use `model_fields` instead:DeprecationWarning:langchain_core.tools.base
